---
title: "JSC370 Homework 5"
author: "Jianhong Guo"
date: "05/04/2022"
output: 
  html_document:
    toc: True
    toc_float: True
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, eval=TRUE)
```

# Intruduction

The dataset for this project is life expectancy data. It contains the health factors and economic data for 193 countries from year 2000 to 2015. What's more, the health factor data is collected from World Health Organization (WHO) while the economic data is from the United Nation website. Life expectancy data contains 2938 rows, and each row is about the life expectancy related information for a country in a specific year. The data set has 22 columns, including the immunization, mortality, economy and society related information. Specifically, Life expectancy data includes variables "Country", "Year", "Status", "Life expectancy", "GDP", "Adult Mortality", "BMI", "Schooling", "Hepatitis B", "Alcohol" and so on. 

The question that we are going to answer based on this dataset is as following:
For the given life expectancy related variables, which variables greatly affect the life expectancy? How those factors affect the life expectancy?

By knowing the above question, we may change situation of the specific variables to improve the life expectancy of a person/ country, and we can use the variables to generate an effective model to predict the life expectancy by given information.

This data set is download from Kaggle(https://www.kaggle.com/kumarajarshi/life-expectancy-who). 
